### ISSUE TITLE
Layout does not look well in WEB browser

### ISSUE THREAD

**Issue by joelstahre** [calebnance/expo-multi-screen-starter#20]
Hey, first of all, awesome job, is it intentional that it does not work in Web Browser? See screenshot:
![image](https://user-images.githubusercontent.com/2317917/80285325-5ef66580-8724-11ea-8185-b0793d22c4d5.png)

Looks good on EXPO client

**Comment by calebnance** [comment]
hey! thanks so much. it's not intended to look that way. i did a lot of this exploration when expo was starting their beta support and also paired with an older version of react-navigation. i know they've done a ton of work getting this closer to a v.1 release but idk if it's there yet. i do want to get this back up to be supported better but not on my radar right now. i would check out some of evan bacon's repos since he's heading up the web support

**Comment by joelstahre** [comment]
I see, thanks anyway! will take a look at evan bacon repos.

**Comment by calebnance** [comment]
@joelstahre hey if you download the latest and `yarn` then `yarn web` everything should be displaying correctly. cheers
